services:
  gateway:
    image: openjdk:17-alpine
    container_name: gateway
    hostname: gateway
    ports:
      - "8080:8080" # Пробрасываем дефолтный порт
    volumes:
    - ./:/app
    working_dir: /app/gateway
    command: /app/gateway/mvnw spring-boot:run  # Используем полный путь
    networks:
      - microservices-network

  user-service:
    image: openjdk:17-alpine
    container_name: user-service
    hostname: user-service
    ports:
      - "8081:8080" # Пробрасываем порт 8080 контейнера на 8081 хоста
    volumes:
    - ./:/app
    working_dir: /app/user-service
    command: /app/user-service/mvnw spring-boot:run  # Используем полный путь
    depends_on:
      - user-db
    networks:
      - microservices-network

  policy-service:
    image: openjdk:17-alpine
    container_name: policy-service
    hostname: policy-service
    ports:
      - "8082:8080" # Пробрасываем порт 8080 контейнера на 8082 хоста
    volumes:
    - ./:/app
    working_dir: /app/insure-policy
    command: /app/insure-policy/mvnw spring-boot:run  # Используем полный путь
    depends_on:
      - policy-db
      - user-service
    networks:
      - microservices-network

  user-db:
    image: postgres:13-alpine
    container_name: user-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: userdb
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  policy-db:
    image: postgres:13-alpine
    container_name: policy-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: policydb
    volumes:
      - policy_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ax@micro.kz
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "7313:80"
    depends_on:
      - user-db
      - policy-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  user_db_data:
  policy_db_data:
  pgadmin_data:
