version: '3'

services:
  app:
    image: openjdk:17-alpine
    hostname: spring-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    depends_on:
      - pg
    networks:
      - my_network
      
  pg:
    image: postgres:13-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/pgsql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: user-service
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: axgiri@ax.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "7313:80"
    depends_on:
      - pg
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - my_network

volumes:
  pg_data:
    driver: local
  pgadmin_data:
    driver: local
    
networks:
  my_network:
    driver: bridge
